#!/bin/bash

ARG1="corewar"
ARG2="../resources/corewar"
RESULT="result.txt"
TEST1="test1.txt"
TEST2="test2.txt"

champa[0]="-v 31 -a ../resources/champion_compilees/helltrain.cor"
champa[1]="-v 31 -a ../resources/champion_compilees/maxidef.cor"
champa[2]="-v 31 -a ../resources/champion_compilees/Gagnant.cor"
champa[3]="-v 31 -a ../resources/champion_compilees/Octobre_Rouge_V4.2.cor"
champa[4]="-v 31 -a ../resources/champion_compilees/bigzork.cor"
champa[5]="-v 31 -a ../resources/champion_compilees/ex.cor"
champa[6]="-v 31 -a ../resources/champion_compilees/fluttershy.cor"
champa[7]="-v 31 -a ../resources/champion_compilees/jumper.cor"
champa[8]="-v 31 -a ../resources/champion_compilees/mortel.cor"
champa[9]="-v 31 -a ../resources/champion_compilees/slider2.cor"
champa[10]="-v 31 -a ../resources/champion_compilees/toto.cor"
champa[11]="-v 31 -a ../resources/champion_compilees/turtle.cor"
champa[12]="-v 31 -a ../resources/champion_compilees/zork.cor"

champv[0]="-v 31 ../resources/champion_compilees/helltrain.cor"
champv[1]="-v 31 ../resources/champion_compilees/maxidef.cor"
champv[2]="-v 31 ../resources/champion_compilees/Gagnant.cor"
champv[3]="-v 31 ../resources/champion_compilees/Octobre_Rouge_V4.2.cor"
champv[4]="-v 31 ../resources/champion_compilees/bigzork.cor"
champv[5]="-v 31 ../resources/champion_compilees/ex.cor"
champv[6]="-v 31 ../resources/champion_compilees/fluttershy.cor"
champv[7]="-v 31 ../resources/champion_compilees/jumper.cor"
champv[8]="-v 31 ../resources/champion_compilees/mortel.cor"
champv[9]="-v 31 ../resources/champion_compilees/slider2.cor"
champv[10]="-v 31 ../resources/champion_compilees/toto.cor"
champv[11]="-v 31 ../resources/champion_compilees/turtle.cor"
champv[12]="-v 31 ../resources/champion_compilees/zork.cor"

champd[0]="-v 2 -d 1 ../resources/champion_compilees/helltrain.cor"
champd[1]="-v 2 -d 1 ../resources/champion_compilees/maxidef.cor"
champd[2]="-v 2 -d 1 ../resources/champion_compilees/Gagnant.cor"
champd[3]="-v 2 -d 1 ../resources/champion_compilees/Octobre_Rouge_V4.2.cor"
champd[4]="-v 2 -d 1 ../resources/champion_compilees/bigzork.cor"
champd[5]="-v 2 -d 1 ../resources/champion_compilees/ex.cor"
champd[6]="-v 2 -d 1 ../resources/champion_compilees/fluttershy.cor"
champd[7]="-v 2 -d 1 ../resources/champion_compilees/jumper.cor"
champd[8]="-v 2 -d 1 ../resources/champion_compilees/mortel.cor"
champd[9]="-v 2 -d 1 ../resources/champion_compilees/slider2.cor"
champd[10]="-v 2 -d 1 ../resources/champion_compilees/toto.cor"
champd[11]="-v 2 -d 1 ../resources/champion_compilees/turtle.cor"
champd[12]="-v 2 -d 1 ../resources/champion_compilees/zork.cor"

champo[0]="-v 2 -s 10 -a ../resources/champion_compilees/helltrain.cor"
champo[1]="-v 2 -s 10 -a ../resources/champion_compilees/maxidef.cor"
champo[2]="-v 2 -s 10 -a ../resources/champion_compilees/Gagnant.cor"
champo[3]="-v 2 -s 10 -a ../resources/champion_compilees/Octobre_Rouge_V4.2.cor"
champo[4]="-v 2 -s 10 -a ../resources/champion_compilees/bigzork.cor"
champo[5]="-v 2 -s 10 -a ../resources/champion_compilees/ex.cor"
champo[6]="-v 2 -s 10 -a ../resources/champion_compilees/fluttershy.cor"
champo[7]="-v 2 -s 10 -a ../resources/champion_compilees/jumper.cor"
champo[8]="-v 2 -s 10 -a ../resources/champion_compilees/mortel.cor"
champo[9]="-v 2 -s 10 -a ../resources/champion_compilees/slider2.cor"
champo[10]="-v 2 -s 10 -a ../resources/champion_compilees/toto.cor"
champo[11]="-v 2 -s 10 -a ../resources/champion_compilees/turtle.cor"
champo[12]="-v 2 -s 10 -a ../resources/champion_compilees/zork.cor"

champs[0]="-v 2 -s 1 ../resources/champion_compilees/helltrain.cor"
champs[1]="-v 2 -s 1 ../resources/champion_compilees/maxidef.cor"
champs[2]="-v 2 -s 1 ../resources/champion_compilees/Gagnant.cor"
champs[3]="-v 2 -s 1 ../resources/champion_compilees/Octobre_Rouge_V4.2.cor"
champs[4]="-v 2 -s 1 ../resources/champion_compilees/bigzork.cor"
champs[5]="-v 2 -s 1 ../resources/champion_compilees/ex.cor"
champs[6]="-v 2 -s 1 ../resources/champion_compilees/fluttershy.cor"
champs[7]="-v 2 -s 1 ../resources/champion_compilees/jumper.cor"
champs[8]="-v 2 -s 1 ../resources/champion_compilees/mortel.cor"
champs[9]="-v 2 -s 1 ../resources/champion_compilees/slider2.cor"
champs[10]="-v 2 -s 1 ../resources/champion_compilees/toto.cor"
champs[11]="-v 2 -s 1 ../resources/champion_compilees/turtle.cor"
champs[12]="-v 2 -s 1 ../resources/champion_compilees/zork.cor"

champm[0]="-v 31 ../resources/champion_compilees/helltrain.cor ../resources/champion_compilees/maxidef.cor ../resources/champion_compilees/Gagnant.cor ../resources/champion_compilees/Octobre_Rouge_V4.2.cor"
champm[1]="-v 31 ../resources/champion_compilees/maxidef.cor ../resources/champion_compilees/bigzork.cor ../resources/champion_compilees/ex.cor ../resources/champion_compilees/fluttershy.cor"
champm[2]="-v 31 ../resources/champion_compilees/Gagnant.cor ../resources/champion_compilees/mortel.cor"
champm[3]="-v 31 ../resources/champion_compilees/Octobre_Rouge_V4.2.cor ../resources/champion_compilees/turtle.cor ../resources/champion_compilees/jumper.cor"
champm[4]="-v 31 ../resources/champion_compilees/bigzork.cor ../resources/champion_compilees/zork.cor"
champm[5]="-v 31 ../resources/champion_compilees/ex.cor ../resources/champion_compilees/ex.cor"
champm[6]="-v 31 ../resources/champion_compilees/fluttershy.cor ../resources/champion_compilees/toto.cor"
champm[7]="-v 31 ../resources/champion_compilees/jumper.cor ../resources/champion_compilees/mortel.cor ../resources/champion_compilees/slider2.cor"
champm[8]="-v 31 ../resources/champion_compilees/mortel.cor ../resources/champion_compilees/helltrain.cor ../resources/champion_compilees/Gagnant.cor"
champm[9]="-v 31 ../resources/champion_compilees/slider2.cor ../resources/champion_compilees/turtle.cor"
champm[10]="-v 31 ../resources/champion_compilees/toto.cor ../resources/champion_compilees/maxidef.cor ../resources/champion_compilees/turtle.cor ../resources/champion_compilees/Gagnant.cor"
champm[11]="-v 31 ../resources/champion_compilees/turtle.cor ../resources/champion_compilees/Octobre_Rouge_V4.2.cor ../resources/champion_compilees/turtle.cor"
champm[12]="-v 31 ../resources/champion_compilees/zork.cor ../resources/champion_compilees/zork.cor ../resources/champion_compilees/zork.cor ../resources/champion_compilees/zork.cor"

champms[0]="-s 1 ../resources/champion_compilees/helltrain.cor ../resources/champion_compilees/maxidef.cor ../resources/champion_compilees/Gagnant.cor ../resources/champion_compilees/Octobre_Rouge_V4.2.cor"
champms[1]="-s 1 ../resources/champion_compilees/maxidef.cor ../resources/champion_compilees/bigzork.cor ../resources/champion_compilees/ex.cor ../resources/champion_compilees/fluttershy.cor"
champms[2]="-s 1 ../resources/champion_compilees/Gagnant.cor ../resources/champion_compilees/mortel.cor"
champms[3]="-s 1 ../resources/champion_compilees/Octobre_Rouge_V4.2.cor ../resources/champion_compilees/turtle.cor ../resources/champion_compilees/jumper.cor"
champms[4]="-s 1 ../resources/champion_compilees/bigzork.cor ../resources/champion_compilees/zork.cor"
champms[5]="-s 1 ../resources/champion_compilees/ex.cor ../resources/champion_compilees/ex.cor"
champms[6]="-s 1 ../resources/champion_compilees/fluttershy.cor ../resources/champion_compilees/toto.cor"
champms[7]="-s 1 ../resources/champion_compilees/jumper.cor ../resources/champion_compilees/mortel.cor ../resources/champion_compilees/slider2.cor"
champms[8]="-s 1 ../resources/champion_compilees/mortel.cor ../resources/champion_compilees/helltrain.cor ../resources/champion_compilees/Gagnant.cor"
champms[9]="-s 1 ../resources/champion_compilees/slider2.cor ../resources/champion_compilees/turtle.cor"
champms[10]="-s 1 ../resources/champion_compilees/toto.cor ../resources/champion_compilees/maxidef.cor ../resources/champion_compilees/turtle.cor ../resources/champion_compilees/Gagnant.cor"
champms[11]="-s 1 ../resources/champion_compilees/turtle.cor ../resources/champion_compilees/Octobre_Rouge_V4.2.cor ../resources/champion_compilees/turtle.cor"
champms[12]="-s 1 ../resources/champion_compilees/zork.cor ../resources/champion_compilees/zork.cor ../resources/champion_compilees/zork.cor ../resources/champion_compilees/zork.cor"

name[0]="helltrain.cor"
name[1]="maxidef.cor"
name[2]="Gagnant.cor"
name[3]="Octobre_Rouge_V4.2.cor"
name[4]="bigzork.cor"
name[5]="ex.cor"
name[6]="fluttershy.cor"
name[7]="jumper.cor"
name[8]="mortel.cor"
name[9]="slider2.cor"
name[10]="toto.cor"
name[11]="turtle.cor"
name[12]="zork.cor"

make DEBUG=1
for i in ${!champs[@]}; do
echo ${name[i]}
./corewar ${champs[i]} > $TEST1
./$ARG2 ${champs[i]} > $TEST2
cmp -b $TEST1 $TEST2 > $RESULT
cat $RESULT
if [ -s "$RESULT" ] ; then
	echo -e '\033[5;31;40m KO \033[0m'
else
	echo -e '\033[5;32;40m OK \033[0m'
fi
done
